site_name: Documentation of RobotDART
site_dir: '../../docs'
site_author: 'Konstantinos Chatzilygeroudis, Jean-Baptiste Mouret'
copyright: 'Konstantinos Chatzilygeroudis, Jean-Baptiste Mouret'
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: index.md
  - Supported robots: robots.md
  - FAQ: faq.md
markdown_extensions:
  - attr_list
plugins:
    - search
    - macros:
        module_name: include/macros
        include_dir: include
