site_name: Documentation of RobotDART
site_dir: '../../docs'
site_author: 'Konstantinos Chatzilygeroudis, Dionis Totsila, Jean-Baptiste Mouret'
copyright: 'Konstantinos Chatzilygeroudis, Dionis Totsila, Jean-Baptiste Mouret'
theme:
  name: null
  custom_dir: 'cinder'
  features:
    - content.code.annotate
    - content.tabs.link
nav:
  - Home: index.md
  - Supported robots: robots.md
  - FAQ: faq.md
  - Install: install.md
markdown_extensions:
  - attr_list
  # - pymdownx.highlight
  # - pymdownx.superfences
  - pymdownx.snippets:
      base_path: '../../'
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


plugins:
    - search
    - macros:
        module_name: include/macros
        include_dir: include
